language: node_js

node_js:
  - "8.15.0"

before_script:
  - npm install -g ganache-cli 
  - npm install -g truffle
  - npm install 

script:
  - ganache-cli -p 8545 > /dev/null &
  - sleep 5
  - truffle migrate --network development 
  - truffle test --network development

