language: node_js

node_js:
	- "8.15.0"

before_script:
  - npm install -g ganache-cli 
  - npm install -g truffle

script:
	- ganache-cli -p 7545 > /dev/null &
	- sleep 5
	- truffle migrate 
	- truffle test

